project:
  type: website

website:
  title: "Sierra Grey-Coker"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - example_analysis.qmd
      

format:
  html:
    theme: pulse
    css: styles.css
    toc: true



